// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrations need a non-pooled connection (PgBouncer's transaction mode
    // doesn't support the prepared statements `prisma migrate` relies on);
    // the app's PrismaClient is pointed at the pooled DATABASE_URL instead,
    // see src/lib/db.ts
    url: process.env["DIRECT_URL"],
  },
});
